#############################################################################
#                                                                           #
# appveyor.yml                                                              #
#                                                                           #
# Author: Denes Solti                                                       #
#                                                                           #
#############################################################################

# common configuration for ALL branches
image: Visual Studio 2022

environment:
  COVERALLS_REPO_TOKEN:  
    secure: 7MfvIuvrUWcs4nKjyLY/izB23UNNMLo3R/EeDhjKaXgNp5AABe3HMPzk1VFJSqDG
# APPVEYOR_RDP_PASSWORD:
#   secure: IvxSZoWD+DpqNjUP7mFjPA==

branches:
  # blacklist
  except:
    - gh-pages

# prevent MSBuild from running
build: off

# enable RDP
# init:
#   - ps: IEX ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# clone repo & submodules
clone_script:
  - cmd: |
      git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      git checkout -qf %APPVEYOR_REPO_COMMIT%

test_script:
  - ps: .\Run-Tests.ps1

after_test:
  - ps: .\Push-TestResults.ps1

# after build failure or success
#on_finish:
#  - ps: |
#     $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
