services:
  localstack:
    image: localstack/localstack:latest
    restart: always
    ports:
      - "4566:4566"
    environment:
      - SERVICES=secretsmanager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  localstack-setup:
    depends_on:
      - localstack
    build: ./SRC/Tools/LocalStack
    environment:
      - LOCALSTACK_ENDPOINT_URL=http://localstack:4566
      - ADMIN_USER=admin
      - ADMIN_PW=cica
  api:
    depends_on:
      localstack-setup:
        condition: service_completed_successfully
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - CONFIG=Debug
    ports:
      - 1986:1986
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - PREFIX=local 