FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /build

ENV DOTNET_NOLOGO=true
ENV DOTNET_CLI_TELEMETRY_OPTOUT=true

COPY DbMigrator ./DbMigrator
COPY Common.targets .

RUN dotnet build DbMigrator/DbMigrator.csproj -o ./bin 

# ---------------------------------------------------

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS base
WORKDIR /app

COPY --from=build build/bin .

ENV DOTNET_NOLOGO=true
ENV DOTNET_CLI_TELEMETRY_OPTOUT=true

ENTRYPOINT ["dotnet", "Warehouse.Tools.DbMigrator.dll"]